services:
  django:
    build: .
    container_name: woozie-app
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/woozieapp  # Corrected syntax
    ports:
      - "8000:8000"
    environment:
      - DEBUG=1
      - DJANGO_ALLOWED_HOSTS=localhost,127.0.0.1
      - CELERY_BROKER=redis://redis:6379/0
      - CELERY_BACKEND=redis://redis:6379/0
    depends_on:
      - db
      - redis

  celery:
    build: .
    command: celery -A woozie worker --loglevel=info
    volumes:
      - .:/woozieapp  # Corrected syntax
    depends_on:
      - django
      - redis
      - db

  db:
    image: postgres
    container_name: pg_db
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - pgdata:/var/lib/postgresql/data  # Removed trailing slash
    ports:
      - "5432:5432"  # Optional: expose PostgreSQL port

  redis:
    image: redis:alpine

volumes:
  pgdata:  # Named volume definition
