# Generated by Django 4.2.11 on 2024-03-23 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='postal_code',
        ),
        migrations.AddField(
            model_name='order',
            name='phone_no',
            field=models.IntegerField(default='0'),
        ),
    ]
